### ISSUE TITLE
FR3. Graphical Representation(s) of Expenses

### ISSUE THREAD

**Issue by shreejakannan** [WSU-4110/Expense-Tracker#3]
|FR3. Graphical Representation(s) of Expenses|
|---|
|**Goal:**   The system will display a pie chart of the user's total expenses  
**Stakeholders:** General Users|
| **Description:** When a user enters their dashboard, it will display a graphical image of the total expense of the user separated by category. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |  
|**Date:** 09/28/2021  
|  **Priority:** 10 |

**Comment by donyellw** [comment]
completed through piechart1.html in sprint 1
